### ISSUE TITLE
Dependency conflicts with Home Assistant 2024.8

### ISSUE THREAD

**Issue by andreasbrett** [basilfx/aiobiketrax#113]
With HA 2024.8 there is a dependency conflict with aiobiketrax. Here's the error I receive when starting up HA 2024.8.b0.

```
Unable to install package aiobiketrax==1.3.0: ERROR: Cannot install aiobiketrax==1.3.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by andreasbrett** [comment]
More specifically:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
homeassistant 2024.8.0b0 requires aiohttp==3.10.0, but you have aiohttp 3.9.5 which is incompatible.
yalexs 6.4.3 requires python-dateutil<3.0.0,>=2.9.0.post0, but you have python-dateutil 2.9.0 which is incompatible.
```

**Comment by basilfx** [comment]
Thank you for reporting. I see that I probably made a mistake and pinned `aiohttp` to a fixed version `3.9.5` instead of `^3.9.5`.

**Comment by andreasbrett** [comment]
> Thank you for reporting. I see that I probably made a mistake and pinned `aiohttp` to a fixed version `3.9.5` instead of `^3.9.5`.

Glad to hear that. I wasn't sure if you deliberately pinned it.

**Comment by basilfx** [comment]
No, not deliberately. At least, I don't recall ;-)

I'm working on this right now. Will validate this with 2024.7 and 2024.8 beta.

**Comment by basilfx** [comment]
It should be solved now. Thank you for testing ahead of the 2024.8 release.

aiobiketrax got updated to 1.3.1 and homeassistant-biketrax got updated to 2.0.1.
