### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by logsoft** [basilfx/aiobiketrax#32]
something not right here

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/biketrax/coordinator.py", line 111, in _async_update_data
    await device.update_subscription()
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/client.py", line 184, in update_subscription
    ] = await self._account.admin_api.get_subscription(self._device.unique_id)
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/api.py", line 424, in get_subscription
    return models.subscription_from_dict(response)
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/models.py", line 802, in subscription_from_dict
    return Subscription.from_dict(s)
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/models.py", line 612, in from_dict
    trial_duration = from_int(obj.get("trialDuration"))
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/models.py", line 47, in from_int
    assert isinstance(x, int) and not isinstance(x, bool)
AssertionError

**Comment by basilfx** [comment]
Thanks for the report.

Are you on the latest alpha version (0.2.2a1)? If so, can you enable debug logging (see here: https://github.com/basilfx/homeassistant-biketrax#debug-logging) and provide some more logging of the responses? Be sure to remove sensitive data.

It's probably an easy fix, but I need to know what value I can expect in the `trialDuration` property.

**Comment by basilfx** [comment]
You can install a pre-release version using this: https://hacs.xyz/docs/faq/beta/

**Comment by logsoft** [comment]
honestly i dont know which version homeassistant installed and where to find that info.
In homeassistant i dont get usefull debug info as its crashing before it can display the fetched data.

but debugging it in pycharm i see theres just no "trialDuration" value in the json data in api.py, line 268 so in the assert has to crash in the "from dict" function then.

this is the json data, with the values replaced:

[{'id': 123456, 'attributes': {'subId': 'substring', 'uploadFrequency': 10, 'guarded': False, 'gprsInStandby': False, 'autoArm': True, 'gsmInStandby': False, 'subPlan': {'interval_count': 1, 'amount': 332, 'metadata': {}, 'product': 'productstring', 'tiers': None, 'livemode': True, 'created': 1234567890, 'transform_usage': None, 'active': True, 'aggregate_usage': None, 'billing_scheme': 'per_unit', 'trial_period_days': 365, 'tiers_mode': None, 'usage_type': 'licensed', 'nickname': 'Monthly', 'currency': 'eur', 'interval': 'month', 'id': 'basic-monthly-plan-id', 'object': 'plan'}, 'alarm': False, 'subCurrentPeriodEnd': '2000-00-00T00:00:00.000Z', 'lowbatteryAlarm': True, 'subStatus': 'trialing', 'trialEnd': '2000-00-00T00:00:00.000Z', 'passport': {'bikePictures': ['http://res.cloudinary.com/powunity/image/upload/v1234567890/production/passport/substring.jpg'], 'receiptPictures': [], 'manufacturer': 'manufacture', 'model': 'model', 'modelYear': '2000-00-00T00:58:00+01:00'}, 'subscriptionPending': False, 'subscription': {'id': 'substring', 'plan_id': 'biketrax-service-plan-12m', 'plan_quantity': 1, 'plan_unit_price': 3950, 'billing_period': 1, 'billing_period_unit': 'year', 'customer_id': 'substring', 'plan_amount': 3950, 'plan_free_quantity': 0, 'status': 'active', 'current_term_start': 1234567890, 'current_term_end': 1234567890, 'next_billing_at': 1234567890, 'created_at': 1234567890, 'started_at': 1234567890, 'activated_at': 1234567890, 'created_from_ip': '0.0.0.0', 'updated_at': 1234567890, 'has_scheduled_changes': False, 'resource_version': 1234567890, 'deleted': False, 'object': 'subscription', 'currency_code': 'EUR', 'due_invoices_count': 0, 'mrr': 274, 'exchange_rate': 1, 'base_currency_code': 'EUR', 'cf_device_id': 1234567890, 'channel': 'web', 'meta_data': {'paidUntil': '20200-00-00T17:42:51.000Z'}}, 'lastAlarm': 1234567890, 'guardType': 'movement'}, 'groupId': 0, 'name': 'name', 'uniqueId': '1234567890', 'status': 'offline', 'lastUpdate': '2022-10-08T22:24:35.678+00:00', 'positionId': 1234567890, 'geofenceIds': [], 'phone': None, 'model': None, 'contact': None, 'category': None, 'disabled': False}]

**Comment by basilfx** [comment]
I have created a fix that makes that field optional. Can you see if replacing `/usr/local/lib/python3.10/site-packages/aiobiketrax/models.py` with [this](https://github.com/basilfx/aiobiketrax/blob/feature/trial_duration/aiobiketrax/models.py) version solves the problem? It requires the 0.2.2a1 release.

If you have installed the integration via HACS, then you can see the version over there (see the link I provided above).

I'm currently testing other fixes that will take some time (stability tests), so I will create a new pre-release after testing has finished.

**Comment by logsoft** [comment]
saw your second message too late, but it doesn't change the underlying problem of this module

**Comment by logsoft** [comment]
hi your fix is working for me here!
thanks!

**Comment by basilfx** [comment]
Thanks for letting me know. I will include this fix in the next release.

**Comment by logsoft** [comment]
i close that now
