### ISSUE TITLE
Error retrieving subscriptions

### ISSUE THREAD

**Issue by jegmond** [basilfx/aiobiketrax#94]
When using the biketrax for homeassistant i get an error message. It seems to be related to the update of the subscription.
Using a small test python-script it seems to be related to the addonids

```
File "/home/local/src/local/biketrax/aiobiketrax/aiobiketrax/models.py", line 259, in from_dict
    addon_ids = from_union(
File "/home/local/src/local/biketrax/aiobiketrax/aiobiketrax/models.py", line 30, in from_union
    assert False
```

The data retrieved from the API is returned as json with a 200 as can be seen in the line below (idenfiers have been modified)
`2023-10-27 19:20:57.814 DEBUG (MainThread) [aiobiketrax.api.responses] {'id': 11111, 'createdAt': '2023-04-24T12:51:34.000Z', 'updatedAt': '2023-10-25T15:33:00.000Z', 'subscriptionId': '11A1aaAaaAaAAAAAa', 'category': 'B2C', 'trialDuration': 365, 'setupFee': None, 'trialEnd': '2025-10-24T15:29:06.000Z', 'addonIds': 'AA0-A-0000', 'uniqueId': '1111111111'}
`
It looks like it doesn't expect addonIds to be a str.

**Comment by basilfx** [comment]
I guessed it would be an array, but I was wrong, hehe.

I've create a pre-release that includes a fix for this. Can you try to upgrade aiobiketrax to v1.1.2a1? Simply change the `custom_components/biketrax/manifest.json`, then restart Home Assistant.

**Comment by jegmond** [comment]
upgraded, restarted and no more error so thanks for the quick fix
